### ISSUE TITLE
Vertical and horizontal scrollbar not displayed in the lateral panel

### ISSUE THREAD

**Issue by fflorent** [firebug/websocket-monitor#16]
STR : 
1. Open the lateral panel with the details of a WS
2. Press Esc to open the split console
3. Expand the height of the console so a scrollbar should appear

Actual result : There is no scrollbar in the lateral panel.

Florent

**Comment by janodvarko** [comment]
I can see a scrollbar, see my screenshot...
Or should I look somewhere else?

Honza

![scrollbar](https://cloud.githubusercontent.com/assets/37785/10482196/93682b2c-7276-11e5-9da2-c117b0b725a9.png)

**Comment by fflorent** [comment]
Yep, you have them. It looks like a specific issue with the Linux theme. I'll take a screenshot once at home.

Florent

**Comment by janodvarko** [comment]
This commit should fix that.
Please let me know if it helps.

Honza

**Comment by fflorent** [comment]
Have checked that right know and that works like a charm. I close the issue.

Florent

**Comment by janodvarko** [comment]
Cool, thanks for the update.
Honza
