### ISSUE TITLE
missing try build

### ISSUE THREAD

**Issue by benfoxall** [firebug/websocket-monitor#26]
The "try build" link on the [releases](https://github.com/firebug/websocket-monitor/releases) page is [404'ing](http://ftp-ssl.mozilla.org/pub/firefox/try-builds/jodvarko@mozilla.com-f2f5f21abb6d/).

**Comment by janodvarko** [comment]
Ah, I see, I pushed another request to the build server now, builds should be avaialble soon
https://ftp-ssl.mozilla.org/pub/mozilla.org/firefox/try-builds/jodvarko@mozilla.com-7871b7dff49f
Honza

**Comment by benfoxall** [comment]
Thanks @janodvarko!

**Comment by janodvarko** [comment]
Just for me, treeherder link:
https://treeherder.mozilla.org/#/jobs?repo=try&revision=7871b7dff49f

Honza

**Comment by janodvarko** [comment]
Pushing one more time:
https://treeherder.mozilla.org/#/jobs?repo=try&revision=69e9a3c36e7e

Once completed, builds and logs will be available at:
https://ftp-ssl.mozilla.org/pub/mozilla.org/firefox/try-builds/jodvarko@mozilla.com-69e9a3c36e7e

Honza

**Comment by janodvarko** [comment]
@benfoxall does this build work for you?
https://ftp-ssl.mozilla.org/pub/firefox/try-builds/amarchesini@mozilla.com-7e726ee90098d0813f0078af282980118f8487f1/

Honza

**Comment by benfoxall** [comment]
@janodvarko yup, that works fine (I'm using the osx build)

**Comment by janodvarko** [comment]
@benfoxall great.

Btw. I'd love to have some feedback from you (missing features, better UI/UX, etc.)

Honza

**Comment by benfoxall** [comment]
@janodvarko sure! That's been on [my list](https://github.com/benfoxall/benfoxall.github.com/issues/52) since @aliuk2012 was in touch about the project.  Looking forward to checking it out.

**Comment by janodvarko** [comment]
Yes, he mentioned that, awesome!

Honza

**Comment by janodvarko** [comment]
Required platform API just landed in Nightly and so, WebSockets Monitor can run with regular Nightly builds. 

https://nightly.mozilla.org/

Honza
