### ISSUE TITLE
Keyboard navigation for list of frames

### ISSUE THREAD

**Issue by janodvarko** [firebug/websocket-monitor#27]
Support up and down keys for keyboard navigation in the frame list. Both perspectives (list view, table view) must be supported.

Honza

**Comment by fflorent** [comment]
Sounds like you fixed it, right? Or is there any further development to do?

Florent

**Comment by janodvarko** [comment]
Yes, the panel should auto-scroll if the selection moves out of the visible viewport.

Honza

**Comment by janodvarko** [comment]
Now it should be alright
Honza
