### ISSUE TITLE
WAMP support

### ISSUE THREAD

**Issue by darkl** [firebug/websocket-monitor#32]
I think it could be cool to add [WAMP support](http://wamp-proto.org/), similarly to Socket.IO support and SockJS support.

WAMP is an open standard WebSocket subprotocol that provides messaging patterns of remote procedure calls and publish subscribe. WAMP has implementations in various languages and is becoming more popular.

I'd love to have support for this.

cc: @oberstet

**Comment by oberstet** [comment]
Oh, cool! I agree, would be quite handy developing browser frontends in WAMP based apps.

Am 20.11.2015 7:54 nachm. schrieb Elad Zelingher notifications@github.com:

I think it could be cool to add WAMP supporthttp://wamp-proto.org/, similarly to Socket.IO support and SockJS support.

WAMP is an open standard WebSocket subprotocol that provides messaging patterns of remote procedure calls and publish subscribe. WAMP has implementations in various languages and is becoming more popular.

I'd love to have support for this.

cc: @oberstethttps://github.com/oberstet

**Comment by janodvarko** [comment]
Sounds good to me. Do you have an online page we could use as as a test case?

Honza

**Comment by oberstet** [comment]
This one

https://demo.crossbar.io/editform/index.html

does perform calls and subscribes to events.

But it doesn't register procedures nor publishes events.

This one performs all 4 WAMP actions (call, register, publish, subscribe), but it's not available as a live demo right now I think.

https://github.com/crossbario/crossbarexamples/tree/master/hello/browser

Am 20.11.2015 11:56 nachm. schrieb Jan Odvarko notifications@github.com:

Sounds good to me. Do you have an online page we could use as as a test case?

Honza

**Comment by oberstet** [comment]
We could also adapt https://github.com/crossbario/autobahn-js/tree/master/package/test which performs a lot of variants and options.

Am 20.11.2015 7:54 nachm. schrieb Elad Zelingher notifications@github.com:

I think it could be cool to add WAMP supporthttp://wamp-proto.org/, similarly to Socket.IO support and SockJS support.

WAMP is an open standard WebSocket subprotocol that provides messaging patterns of remote procedure calls and publish subscribe. WAMP has implementations in various languages and is becoming more popular.

I'd love to have support for this.

cc: @oberstethttps://github.com/oberstet

**Comment by janodvarko** [comment]
I couldn't find any docs describing WAMP message/action structure send  by WAMP subprotocol. Do you know about anything?

Currently, WebSocket monitor displays the payload (at least) as a simple JSON expandable tree (see the attached screenshot), but perhaps we could append some WAMP specific labels to the UI that make it easier to read the data and e.g. recognize type of the action (call, register, publish, subscribe).

![crossbar io](https://cloud.githubusercontent.com/assets/37785/11337806/1b3b935c-91f0-11e5-99d2-608c41e6f93e.png)

Any other tips how representation of WAPM message should actually look like?

Honza

**Comment by oberstet** [comment]
Cool!

Yeah, would be nice to expose WAMP traffic at a higher level: procedure calls and registrations, even publications and topic subscriptions, authenthication and generally session establishment. Please see here for the spec (incl. description of messages) https://tools.ietf.org/html/draft-oberstet-hybi-tavendo-wamp-02

Am 23.11.2015 2:42 nachm. schrieb Jan Odvarko notifications@github.com:

I couldn't find any docs describing WAMP message/action structure send by WAMP subprotocol. Do you know about anything?

Currently, WebSocket monitor displays the payload (at least) as a simple JSON expandable tree (see the attached screenshot), but perhaps we could append some WAMP specific labels to the UI that make it easier to read the data and e.g. recognize type of the action (call, register, publish, subscribe).

[https://cloud.githubusercontent.com/assets/37785/11337806/1b3b935c-91f0-11e5-99d2-608c41e6f93e.png]https://cloud.githubusercontent.com/assets/37785/11337806/1b3b935c-91f0-11e5-99d2-608c41e6f93e.png

Any other tips how representation of WAPM message should actually look like?

Honza

**Comment by oberstet** [comment]
Besides decoding WAMP messages fields, here is what would be highly useful: correlate replies to requests at the WAMP msg level .. eg call and call result ..

Am 23.11.2015 2:42 nachm. schrieb Jan Odvarko notifications@github.com:

I couldn't find any docs describing WAMP message/action structure send by WAMP subprotocol. Do you know about anything?

Currently, WebSocket monitor displays the payload (at least) as a simple JSON expandable tree (see the attached screenshot), but perhaps we could append some WAMP specific labels to the UI that make it easier to read the data and e.g. recognize type of the action (call, register, publish, subscribe).

[https://cloud.githubusercontent.com/assets/37785/11337806/1b3b935c-91f0-11e5-99d2-608c41e6f93e.png]https://cloud.githubusercontent.com/assets/37785/11337806/1b3b935c-91f0-11e5-99d2-608c41e6f93e.png

Any other tips how representation of WAPM message should actually look like?

Honza

**Comment by darkl** [comment]
@janodvarko,

For a start I generated a function that parses WAMP messages in Typescript (using my [meta-wamp](https://github.com/darkl/meta-wamp) project). The transpiled JavaScript is also included. See [here](https://gist.github.com/darkl/d761ab0e680b9722cb2c).

Hope this helps.
Elad

**Comment by janodvarko** [comment]
> For a start I generated a function that parses WAMP messages in Typescript (using my meta-wamp project). The transpiled JavaScript is also included. See here.

Great! I've incorporated it into the code base.

> Besides decoding WAMP messages fields, here is what would be highly useful: correlate replies to requests at the WAMP msg level .. eg call and call result ..

Yes, I like that idea. Can you please create separate issue for this, thanks!

This issue should be fixed in version 0.4.3
https://github.com/firebug/websocket-monitor/releases

Honza

**Comment by darkl** [comment]
Cool, thanks!
