### ISSUE TITLE
Some messages not picked up

### ISSUE THREAD

**Issue by eliihen** [firebug/websocket-monitor#33]
Hi Jan. Nice work with this extension, keep up the good work!

It seems websocket-monitor has issues with some messages. My company produces many pages that stream market data, and the first thing the client does after getting upgraded to WS is send a subscribe string with the data that component would like to receive. In my tests, this client does not pick up these subscribe strings at all.

Steps to reproduce
- Open up google chrome alongside Firefox with your extension
- Open devtools to inspect websockets
- Navigate to https://bors.e24.no/?#!/market/world

In Chrome, the strings show in green as `subscribe?...`. In websocket-monotor, they do not show, only the later response from server to this subscribe string shows up.

WS-monitor 0.4.1 Firefox 45.0a1 (2015-11-20) Fedora Linux

**Comment by janodvarko** [comment]
Thanks for the report, I'll investigate it.

Jan (aka Honza)

**Comment by janodvarko** [comment]
@bakulf: I've been trying the STR and it really looks like some WS messages are missing?
Could this be a problem with the platform API?

Honza

**Comment by tuukka** [comment]
I'm trying to debug MQTT over WebSockets but only some initial handshake is visible: one binary frame sent, one binary frame received, although there's a constant flow of messages. Here's my test page: http://dev.hsl.fi/mqtt/browser/

**Comment by janodvarko** [comment]
@tuukka:

Here is a test build with patch included, does it help?
http://softwareishard.com/temp/websocketmonitor/websocketmonitor-0.5.3issue33.xpi

Honza

**Comment by tuukka** [comment]
@janodvarko I don't see any change (Firefox 45.0 on Ubuntu) :-(

**Comment by janodvarko** [comment]
@tuukka: ah, sorry, I forgot to include the patch in the build, here is a new version:
http://softwareishard.com/temp/websocketmonitor/websocketmonitor-0.5.3issue33-2.xpi

Honza

**Comment by tuukka** [comment]
@janodvarko Thanks, that did the trick!

**Comment by tuukka** [comment]
I also compared the output to the websocket frame view in Chromium, and they match.

**Comment by janodvarko** [comment]
Thanks for the verification!
Honza
