### ISSUE TITLE
Sign Add-on using "jpm sign" doesn't work?

### ISSUE THREAD

**Issue by janodvarko** [firebug/websocket-monitor#37]
We want to sign future released XPIs using `jpm sign`.

Note for me:
https://groups.google.com/forum/#!topic/mozilla.dev.amo/OZz62cJwWCc

Honza

**Comment by lebedev** [comment]
There were some issues with `jpm sign` some time ago and I've encountered them myself, but to date it should work just fine. At least when I sign my unlisted add-on via `jpm sign` (actually, I sign it with

```
var Client = require('jpm/lib/amo-client').Client;
var client = new Client(...);
client.sign(...);
```

which is no big difference), it gets signed just fine.

**Comment by janodvarko** [comment]
The addon is now available on AMO so, this is no longer a problem. Hope this is working for other addons.

Honza
