### ISSUE TITLE
Clear the list of connections in the filter after reload

### ISSUE THREAD

**Issue by janodvarko** [firebug/websocket-monitor#41]
The the list of WS connections in the filter should be cleared up after page reload.

Honza

**Comment by eliihen** [comment]
I can have a look at this when I get the time. Not sure how to detect a page reload though, do you mind to point me in the right direction?

**Comment by janodvarko** [comment]
Take a look at WsmPanel:
- There is a method `onTabNavigated`
- It's registered as a handler for "navigate" event in `onRready`
- It sends a "removeFrames" message to the content (to the iframe where all the ReactJS stuff is)
- The removeFrames message is handled by `WebSocketsView.removeFrames` method

You can rename the message and make it more generic (e.g. `tabNavigated`), and wire the logic related to cleaning up of the dropdown connection list from there (i.e. `WebSocketsView.tabNavigated`).

Let me know if this isn't clear or you don't have time in following couple of weeks (I am having vacation since Dec 17th and this should be fixed and shipped before that :)

Thanks
Honza

**Comment by eliihen** [comment]
Ah, I see. Thanks!

That makes sense, yeah. I'll have some time to work this weekend, so I'm sure we'll manage to work this out by the 17th :)

**Comment by janodvarko** [comment]
Awesome!

**Comment by janodvarko** [comment]
Huh, this took me only 2 months to review :-)
Works for me, thanks!
Honza

**Comment by eliihen** [comment]
Hehe, good thing we're not in a hurry :)
