### ISSUE TITLE
Utf-8 characters are corrupted

### ISSUE THREAD

**Issue by i-void** [firebug/websocket-monitor#43]
In the message "Ãok YakÄ±nda BuradayÄ±z..." must be seen as "Çok Yakında Buradayız"

**Comment by lebedev** [comment]
All cyrillic symbols are messed up as well ("Тестовая фраза на русском" shows as "Ð¢ÐµÑÑÐ¾Ð²Ð°Ñ ÑÑÐ°Ð·Ð° Ð½Ð° ÑÑÑÑÐºÐ¾Ð¼").
It would be great if this add-on support UTF-8.
