### ISSUE TITLE
websocket panel blank

### ISSUE THREAD

**Issue by MoLow** [firebug/websocket-monitor#50]
hey,
first of all - the test page (http://janodvarko.cz/test/websockets/) works perfectly.
in a site I am developing, the websocket panel is just blank.
My socket is using wss (secure websocket), and I tried canceling it, but that did not resolve the issue.
My socket is also not using a standard port, may that be the issue?
I also thought that different domains in the client and the socket could be an issue, but the test page also has a different domain.

![Screenshot](http://snag.gy/RaX0L.jpg)

**Comment by MoLow** [comment]
started working. have no idea what happed :)

**Comment by eliihen** [comment]
Hi, thanks for posting. If it happens again, please do the following:
- Open the browser console (Ctrl+Shift+J)
- Close (if open) and re-open devtools in the browser (F12)
- Clear the browser console
- Click `Web Sockets` in devtools
- Post any errors in the browser console to a new issue.
