### ISSUE TITLE
TypeError: Rdp.registerTabActor(...) is undefined

### ISSUE THREAD

**Issue by jryans** [firebug/websocket-monitor#61]
With WebSocket Monitor 0.6.2 and Nightly 2016-06-06, I get the following:

```
TypeError: Rdp.registerTabActor(...) is undefined
```

and the panel does not load.

**Comment by janodvarko** [comment]
The fix goes to firebug.sdk
https://github.com/firebug/firebug.sdk/commit/bd43add69503dd8b421f8768b2d048bae9642271

(new module path for ActorRegistryFront)

Will be fixed in WebSocket Monitor 0.6.3

Honza

**Comment by janodvarko** [comment]
0.6.3 is on AMO (waiting for review ;-)

Please let me know if the problem is fixed for you now.

Honza

**Comment by jryans** [comment]
Great, that seems to fix it. Review approved on AMO.

**Comment by janodvarko** [comment]
Thanks!
