### ISSUE TITLE
side panel not resizable

### ISSUE THREAD

**Issue by mesteche** [firebug/websocket-monitor#65]
Depending on the socket ID i am monitoring, the side panel (details/payload) is not resizable (and it's default size is ridiculous) :
![image](https://cloud.githubusercontent.com/assets/3534244/18705901/1e0597a6-7ff0-11e6-90c1-c1a018f58cc8.png)
My guess is that it's because I have a "Connected to:" line that is just too long. It's the most noticeable difference between the two Socket IDs.
here is what I have when I select the other socket ID :
![image](https://cloud.githubusercontent.com/assets/3534244/18706046/9ff464d6-7ff0-11e6-84ce-19b0a6767d84.png)

**Comment by eliihen** [comment]
It seems your hypothesis is correct, I am able to reproduce this by going to https://www.websocket.org/echo.html and subscribing to a URL with a very long search.

Thanks for the report, I can have a look at fixing this when I have time

**Comment by eliihen** [comment]
Okay, I've pushed c16357e upstream and it looks good from here. Tested in dev-ed and nightly. @janodvarko, would you like to create a release and submit a new version to AMO?

**Comment by janodvarko** [comment]
Done, thanks for the patch!

WebSocket Monitor 0.6.4 XPI available for download:
https://github.com/firebug/websocket-monitor/releases

... and also awaiting full review on AMO:
https://addons.mozilla.org/en-US/firefox/addon/websocket-monitor/

Honza
