### ISSUE TITLE
Log Http also

### ISSUE THREAD

**Issue by tgkprog** [firebug/websocket-monitor#71]
If I could ask for one feature, it would be to have a check box on the preferences tab "Log Http also". When checked regular Http get, post ... would be logged to. That way I can see the sequence of all network activity of a tab in one place. Thank you for making this open source.

**Comment by eliihen** [comment]
Hi tgkprog, thanks for dropping by.

I'm sorry, I feel this is outside the scope of this extension. We already have the excellent network monitor in the devtools, why reinvent the wheel?
