### ISSUE TITLE
e10s support

### ISSUE THREAD

**Issue by stof** [firebug/websocket-monitor#73]
Does this plugin supports e10s ? https://arewee10syet.com/ marks it as unknown

**Comment by eliihen** [comment]
It does.
I'll add the `multiprocess` permission to the `package.json` file to flag it as compatible

**Comment by stof** [comment]
@esphen any chance to get a release containing the flag ?

**Comment by eliihen** [comment]
Ping @janodvarko

**Comment by janodvarko** [comment]
Done

New release 0.6.5 available (waiting for AMO review)

Honza

**Comment by janodvarko** [comment]
0.6.5 has passed AMO review

**Comment by stof** [comment]
thanks. I'm now enjoying the e10s mode.
