### ISSUE TITLE
Support auto-scroll at the bottom

### ISSUE THREAD

**Issue by janodvarko** [firebug/websocket-monitor#8]
When following constant stream of frames it's useful to have the panel always scrolled at the bottom to see the last incoming packet.

Honza

**Comment by janodvarko** [comment]
Yet the list view doesn't work from some reason.

Honza

**Comment by fflorent** [comment]
> Yet the list view doesn't work from some reason.

Looks like the bubbles are not fully rendered when doing your trick. If you place a breakpoint in `componentDidUpdate`, trigger an update of your view and step over until you reach the end of the function, you'll see your bubble appears be partially rendered. For example, you miss the rendering of the Frame Reps.
- While in `componentDidUpdate`
  ![While in componentDidUpdate](https://cloud.githubusercontent.com/assets/371705/10566586/953e3da6-75eb-11e5-94c2-878f245d518a.png)
- After resuming the debugger:
  ![After resuming the debugge](https://cloud.githubusercontent.com/assets/371705/10566590/b10db9f8-75eb-11e5-8529-ae04471273da.png)

I don't know what would render them lazily (or asynchronously) like this. The TreeView?

Florent

**Comment by janodvarko** [comment]
Thanks for the analyses, I found better solution.
But, I would still be interested to know why the tree is rendered after didmount..

Anyway, it should work now, can you please try it on your machine?

Honza
